In [ ]:
%matplotlib inline


What is PyTorch?
================

It’s a Python-based scientific computing package targeted at two sets of
audiences:

-  A replacement for NumPy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed

Getting Started
---------------

Tensors
^^^^^^^

Tensors are similar to NumPy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.



In [1]:
from __future__ import print_function
import torch

Construct a 5x3 matrix, uninitialized:



In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[-2.5406e+32,  4.5880e-41, -2.5406e+32],
        [ 4.5880e-41, -2.7232e+29,  4.5880e-41],
        [-2.7232e+29,  4.5880e-41, -2.7232e+29],
        [ 4.5880e-41, -2.7232e+29,  4.5880e-41],
        [-2.7232e+29,  4.5880e-41, -2.7274e+29]])


Construct a randomly initialized matrix:



In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.8651, 0.8904, 0.8410],
        [0.6892, 0.9223, 0.0885],
        [0.2132, 0.5516, 0.0373],
        [0.5718, 0.6600, 0.6509],
        [0.7805, 0.4705, 0.1875]])


Construct a matrix filled zeros and of dtype long:



In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Construct a tensor directly from data:



In [8]:
x = torch.tensor([5.5, 3])
print(x)

x2 = torch.tensor([[5.5, 3], [6.5, 4]])
print(x2)

tensor([5.5000, 3.0000])
tensor([[5.5000, 3.0000],
        [6.5000, 4.0000]])


or create a tensor based on an existing tensor. These methods
will reuse properties of the input tensor, e.g. dtype, unless
new values are provided by user



In [27]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-1.2304, -1.2633,  0.1510],
        [ 0.9551,  0.6395,  0.7056],
        [-0.6230,  1.3742, -0.4170],
        [-0.1470,  1.0595,  0.6382],
        [ 0.3211, -1.7196, -1.2600]])


Get its size:



In [28]:
print(x.size())

torch.Size([5, 3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` is in fact a tuple, so it supports all tuple operations.</p></div>

Operations
^^^^^^^^^^
There are multiple syntaxes for operations. In the following
example, we will take a look at the addition operation.

Addition: syntax 1



In [29]:
y = torch.rand(5, 3)
print(x)
print(y)
print(x + y)

tensor([[-1.2304, -1.2633,  0.1510],
        [ 0.9551,  0.6395,  0.7056],
        [-0.6230,  1.3742, -0.4170],
        [-0.1470,  1.0595,  0.6382],
        [ 0.3211, -1.7196, -1.2600]])
tensor([[0.1416, 0.9081, 0.5752],
        [0.8910, 0.7194, 0.4435],
        [0.6131, 0.7810, 0.7218],
        [0.1167, 0.6958, 0.8201],
        [0.1874, 0.8053, 0.1538]])
tensor([[-1.0888, -0.3552,  0.7262],
        [ 1.8461,  1.3589,  1.1492],
        [-0.0098,  2.1552,  0.3047],
        [-0.0303,  1.7553,  1.4583],
        [ 0.5085, -0.9143, -1.1062]])


Addition: syntax 2



In [30]:
print(torch.add(x, y))

tensor([[-1.0888, -0.3552,  0.7262],
        [ 1.8461,  1.3589,  1.1492],
        [-0.0098,  2.1552,  0.3047],
        [-0.0303,  1.7553,  1.4583],
        [ 0.5085, -0.9143, -1.1062]])


Addition: providing an output tensor as argument



In [31]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-1.0888, -0.3552,  0.7262],
        [ 1.8461,  1.3589,  1.1492],
        [-0.0098,  2.1552,  0.3047],
        [-0.0303,  1.7553,  1.4583],
        [ 0.5085, -0.9143, -1.1062]])


Addition: in-place



In [32]:
# adds x to y
y.add_(x)
print(y)

tensor([[-1.0888, -0.3552,  0.7262],
        [ 1.8461,  1.3589,  1.1492],
        [-0.0098,  2.1552,  0.3047],
        [-0.0303,  1.7553,  1.4583],
        [ 0.5085, -0.9143, -1.1062]])


<div class="alert alert-info"><h4>Note</h4><p>Any operation that mutates a tensor in-place is post-fixed with an ``_``.
    For example: ``x.copy_(y)``, ``x.t_()``, will change ``x``.</p></div>

You can use standard NumPy-like indexing with all bells and whistles!



In [37]:
print(x)
print(x[:, 1])

print("Size")
print(x.size())
print(x[:, 1].size())

x3 = torch.rand(7)
print(x3)
print(x3.size())

x4 = torch.rand(1, 7)
print(x4)
print(x4.size())

tensor([[-1.2304, -1.2633,  0.1510],
        [ 0.9551,  0.6395,  0.7056],
        [-0.6230,  1.3742, -0.4170],
        [-0.1470,  1.0595,  0.6382],
        [ 0.3211, -1.7196, -1.2600]])
tensor([-1.2633,  0.6395,  1.3742,  1.0595, -1.7196])
Size
torch.Size([5, 3])
torch.Size([5])
tensor([0.8908, 0.4085, 0.1178, 0.6792, 0.2293, 0.9422, 0.6139])
torch.Size([7])
tensor([[0.8461, 0.7736, 0.8140, 0.0066, 0.6281, 0.1619, 0.5885]])
torch.Size([1, 7])


Resizing: If you want to resize/reshape tensor, you can use ``torch.view``:



In [38]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


If you have a one element tensor, use ``.item()`` to get the value as a
Python number



In [39]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.8306])
-0.8306048512458801


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <https://pytorch.org/docs/torch>`_.

NumPy Bridge
------------

Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

The Torch Tensor and NumPy array will share their underlying memory
locations, and changing one will change the other.

Converting a Torch Tensor to a NumPy Array
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^



In [40]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [42]:
b = a.numpy()
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]


See how the numpy array changed in value.



In [43]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Converting NumPy Array to Torch Tensor
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
See how changing the np array changed the Torch Tensor automatically



In [44]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to
NumPy and back.

CUDA Tensors
------------

Tensors can be moved onto any device using the ``.to`` method.



In [46]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)       
    # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!